/** Human-facing notes for every dither method. */
export const ALGORITHM_COPY: Record<string, string> = {
  'floyd-steinberg': 'Classic 1976 7/16 error diffusion. Organic photo grain, slight rightward crawl. Best default for portraits.',
  'floyd-steinberg-serpentine': 'Floyd\u2013Steinberg with alternating scan direction. Same grain, far less worming.',
  'false-floyd-steinberg': '3-weight FS simplification. Faster, coarser, crunchier.',
  'false-floyd-steinberg-serpentine': 'False FS scanned serpentine. Softens directional bias.',
  jarvis: 'Jarvis\u2013Judice\u2013Ninke wide 12-element kernel. Smoother, more even than FS.',
  'jarvis-serpentine': 'JJN with serpentine scan. The expensive-smooth look.',
  stucki: 'Stucki 12-weight kernel. Sharper cousin of JJN.',
  'stucki-serpentine': 'Stucki serpentine. High-quality photo dither.',
  atkinson: 'Bill Atkinson MacPaint kernel. Only 3/4 error diffused \u2014 airy highlights.',
  'atkinson-serpentine': 'Atkinson serpentine. Same airy highlights, fewer worms.',
  burkes: 'Burkes 7-weight strip. Newspaper middle ground.',
  'burkes-serpentine': 'Burkes serpentine. Even newspaper grain.',
  sierra: 'Full Sierra 10-weight. Soft, filmic.',
  'sierra-serpentine': 'Full Sierra serpentine.',
  'sierra-two-row': 'Sierra trimmed to two rows.',
  'sierra-two-row-serpentine': 'Two-row Sierra serpentine.',
  'sierra-lite': 'Three-weight Sierra. Fast, crunchy, good for video.',
  'sierra-lite-serpentine': 'Sierra Lite serpentine. Live-preview workhorse.',
  'stevenson-arce': 'Sparse wider kernel. Scattered pepper, less FS crawl.',
  'stevenson-arce-serpentine': 'Stevenson\u2013Arce serpentine.',
  'shiau-fan': 'Compact 4-weight kernel that cuts worming vs FS.',
  'shiau-fan-2': 'Wider Shiau\u2013Fan follow-up. Smoother midtones.',
  'fan-93': 'Fan 1993 variable-weight diffusion.',
  'filter-lite': 'Tiny three-tap diffuser. Harsh and fast.',
  'jjn-lite': 'Slimmed Jarvis. Most of the evenness, less cost.',
  ostromoukhov: 'Variable-coefficient FS by luminance. Premium photo dither.',
  riemersma: 'Hilbert-path error history. Organic, painterly.',
  'dot-diffusion': 'Ulichney class-matrix. Clustered printer dots.',
  'bayer-2': 'Bayer 2\u00d72. Chunky, stable under animation.',
  'bayer-4': 'Classic demo-scene 4\u00d74 ordered tile.',
  'bayer-8': 'Finer Bayer lattice. Good for UI chrome.',
  'bayer-16': 'Near-photographic ordered dither.',
  'clustered-4': '4\u00d74 clustered-dot halftone plate.',
  'clustered-8': '8\u00d78 clustered-dot. Offset-print cousin.',
  'diagonal-cluster': 'Clustered dots rotated off-axis.',
  halftone: 'Circular-dot amplitude screen. Newspaper photo.',
  'line-horizontal': 'Horizontal line screen. Engraving cousin.',
  'line-vertical': 'Vertical line screen. Pair with scanlines.',
  'line-diagonal': '45\u00b0 hatch / security-print look.',
  crosshatch: 'Two line screens crossed. Graphite / etching.',
  'dot-screen': 'Round-dot amplitude screen.',
  'ellipse-screen': 'Elliptical cells. Less moir\u00e9 than circles.',
  'dual-screen': 'Two overlapping screens. Built-in shimmer.',
  hilbert: 'Thresholds walked on a Hilbert / Z-order curve.',
  threshold: 'Hard cutoff against the Threshold slider. Pure posterize.',
  random: 'Fresh random threshold per pixel. Twinkles on video.',
  'white-noise': 'White-noise threshold field. Harsh hiss.',
  'blue-noise': 'Multi-octave blue-noise approx. Expensive film grain.',
  gaussian: 'Gaussian-ish threshold jitter. Softer than white.',
  'variable-threshold': 'Low-frequency modulated cut. Painterly bands.',
  peano: 'Peano-ish space-filling threshold.',
  'dithyr-weave': 'Basket-weave threshold. Fabric / wicker.',
  'dithyr-spiral': 'Polar spiral screen. Medals, vinyl, portraits.',
  'dithyr-hex': 'Hex lattice. Honeycomb instead of Bayer.',
  'dithyr-voronoi': 'Jittered Voronoi cells. Cracked-mud tiles.',
  'dithyr-ripple': 'Concentric ripple screen. Strong on gradients.',
  'dithyr-checker': 'Soft checker that grows with tone.',
  'dithyr-diamond': 'Diamond lattice. Faceted, jewelry-ish.',
  'dithyr-circles': 'Packed-circle screen. Bubbly comic halftone.',
  'dithyr-waves': 'Sine-wave interference. Water / flag.',
  'dithyr-grid-soft': 'Soft rectangular grid. Blueprint vibe.',
  'dithyr-pixel-crush': 'Aggressive cell crush. Console chunk.',
  'dithyr-grain-mesh': 'Overlapping noise meshes. Textile material.',
  'dithyr-lattice': 'Rigid lattice with variable strut weight.',
  'dithyr-moire': 'Two beating screens. Maximum shimmer.',
  'dithyr-triad': 'Triangular triad cells.',
  'dithyr-gradient-mesh': 'Cell size follows local gradient magnitude.',
  'dithyr-bloom': 'Error blooms into neighbors. Glowy, less pointillist.',
};

export function describeAlgorithm(id: string, fallback?: string): string {
  return ALGORITHM_COPY[id] ?? fallback ?? 'Quantizes each pixel to the active palette.';
}
